### ISSUE TITLE
is this library compatible with xcode 8 and swift 3?

### ISSUE THREAD

**Issue by swabzz** [FuckBoilerplate/RxCache#10]
[!] Unable to satisfy the following requirements:

`RxSwift (~> 2.0)` required by `RxCache (0.1.4)`

`RxCache (0.1.4)` requires the `RxSwift (~> 2.0)` but `RxSwift (~> 2.0)` is not compatible with swift 3 they are having 'RxSwift',    '~> 3.0.0-beta.1' compatible version .

**Comment by robertofrontado** [comment]
Hello @bagwanshoaib 

Currently I'm working on the compatibility with Swift 3, hope to finish it next week

**Comment by robertofrontado** [comment]
Hey @swabzz, sorry about the delay,

This supports swift 3, but it has a breaking change in the way you add it in your podfile

Now its separated in modules (ObjectMapper, Gloss...)

First add the core:
`pod 'RxCache', '~> 1.0.2'`

And then the module you need:
`pod 'RxCache/ObjectMapper', '~> 1.0.2'`
`pod 'RxCache/Gloss', '~> 1.0.2'`

Let me know if everything works right for you 👍
